version: "3.9"
services:
  app-service:
    image: gotodo
    container_name: app-container
    build:
      args:
        - target=dev
    environment:
      TODO_ENV: dev
      PORT: 8080
      TODO_DB_HOST: todo-db
      TODO_DB_PORT: 3306
      TODO_DB_USER: todo
      TODO_DB_PASSWORD: todo
      TODO_DB_NAME: todo
    volumes:
      - .:/app
    ports:
      - "18000:8080"
    links:
      - todo-db-service
  todo-db-service:
    image: mysql:8.0.29
    platform: linux/amd64
    container_name: todo-db-container
    ports:
      - "33306:3306"
    volumes:
      - todo-db-volumes:/var/lib/mysql
      - $PWD/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
      MYSQL_DATABASE: todo
volumes:
  todo-db-volumes: