# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  DOCKER_TAG: latest

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build-local:
    cmds:
      - docker compose build --no-cache

  up:
    cmds:
      - docker compose up

  down:
    cmds:
      - docker compose down

  logs:
    cmds:
      - docker compose logs -f

  ps:
    cmds:
      - docker compose ps

  test:
    cmds:
      - go test -race -shuffle=on ./...